# Generated by Django 4.2.1 on 2023-06-02 15:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="LocationVO",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("closet_name", models.CharField(max_length=200)),
                ("section_number", models.PositiveSmallIntegerField()),
                ("shelf_number", models.PositiveSmallIntegerField()),
                ("location_href", models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="Hat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fabric", models.CharField(max_length=100)),
                ("style_name", models.CharField(max_length=100)),
                ("color", models.CharField(max_length=100)),
                ("picture_URL", models.CharField(max_length=100)),
                ("wardrobe_location", models.CharField(max_length=100)),
                (
                    "location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hat_location",
                        to="hats_rest.locationvo",
                    ),
                ),
            ],
        ),
    ]
