# Generated by Django 4.0.3 on 2023-06-02 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hats_rest', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hat',
            old_name='picture_URL',
            new_name='picture_url',
        ),
        migrations.RemoveField(
            model_name='hat',
            name='wardrobe_location',
        ),
    ]
