# Generated by Django 4.0.3 on 2023-06-01 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoes_rest', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='binvo',
            name='bin_href',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
