# Generated by Django 4.0.3 on 2023-06-02 02:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shoes_rest', '0002_alter_binvo_bin_href'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='binvo',
            name='bin_href',
        ),
        migrations.RemoveField(
            model_name='shoe',
            name='shoe_bin_location',
        ),
        migrations.RemoveField(
            model_name='shoe',
            name='shoe_color',
        ),
        migrations.RemoveField(
            model_name='shoe',
            name='shoe_make',
        ),
        migrations.RemoveField(
            model_name='shoe',
            name='shoe_model',
        ),
        migrations.RemoveField(
            model_name='shoe',
            name='shoe_picture',
        ),
        migrations.AddField(
            model_name='binvo',
            name='import_href',
            field=models.URLField(null=True, unique=True),
        ),
        migrations.AddField(
            model_name='shoe',
            name='bin',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shoes', to='shoes_rest.binvo'),
        ),
        migrations.AddField(
            model_name='shoe',
            name='color',
            field=models.CharField(default='Red', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shoe',
            name='manufacturer',
            field=models.CharField(default='Nike', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shoe',
            name='model_name',
            field=models.CharField(default='Air Max', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shoe',
            name='picture_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='binvo',
            name='bin_number',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='binvo',
            name='bin_size',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='binvo',
            name='closet_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
