# Generated by Django 4.0.3 on 2023-06-02 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shoes_rest', '0004_remove_binvo_import_href_remove_shoe_bin_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shoe',
            old_name='shoe_bin_location',
            new_name='bin',
        ),
    ]
