# Generated by Django 4.0.3 on 2023-06-02 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shoes_rest', '0005_rename_shoe_bin_location_shoe_bin'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shoe',
            old_name='bin',
            new_name='closet_name',
        ),
    ]
