# Generated by Django 4.0.3 on 2023-06-02 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shoes_rest', '0006_rename_bin_shoe_closet_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shoe',
            old_name='closet_name',
            new_name='bin',
        ),
    ]
