# Generated by Django 4.0.3 on 2023-06-02 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shoes_rest', '0007_rename_closet_name_shoe_bin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='binvo',
            name='bin_number',
        ),
        migrations.RemoveField(
            model_name='binvo',
            name='bin_size',
        ),
    ]
